# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e5d831bf8a885b72da53ce7d152ea1a00bd91d43560035322311d61577a6ca5f96d9493070b7e8afaf6607fa2b3ecbcafffbe6617caab8b671ff694b1099da0

test:
  secret_key_base: c3be947e8d17456934917c9918f51b3cb196e1d5a2c7932c05e8e1c8936e96a1f63c0dd8f6dca8d1b84764aa409dd6bd0fe4fecea92bdcfbc54299be3192cda2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
